apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../base
  - namespace.yaml
  - hpa.yaml

namespace: devops-lab-app-prod-blue

images:
  - name: pipeops/devops-lab-app
    newName: docker.io/flaviopiccolo/devops-lab-app
    newTag: "sha-0e2fac81e0f6585d5914b73a5b67c2554d806e2a"

patches:
  - path: patch-deployment.yaml
  - path: patch-ingress.yaml
  - path: patch-disable-local-postgres.yaml
