apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: devops-lab-app
spec:
  rules:
    - host: devops-lab-app-aws-staging.localtest.me
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: devops-lab-app
                port:
                  number: 80
