apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - deployment.yaml
  - service.yaml
  - ingress.yaml
  - postgres-secret.yaml
  - postgres-pvc.yaml
  - postgres-deployment.yaml
  - postgres-service.yaml

labels:
  - includeSelectors: true
    pairs:
      app.kubernetes.io/name: devops-lab-app
      app.kubernetes.io/part-of: devops-lab

images:
  - name: pipeops/devops-lab-app
    newTag: "sha-7462ef02c1f65208e7e8d9c879563a5b43bb3270"