apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../base
  - namespace.yaml

namespace: devops-lab-app-dev

images:
  - name: pipeops/devops-lab-app
    newName: docker.io/flaviopiccolo/devops-lab-app
    newTag: "sha-9a7c7e34233313be1cf44918c4f667d8bfbe9a2a"
patches:
  - path: patch-deployment.yaml
  - path: patch-ingress.yaml

