apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../base
  - namespace.yaml

namespace: devops-lab-app-dev

images:
  - name: pipeops/devops-lab-app
    newName: docker.io/flaviopiccolo/devops-lab-app
    newTag: "sha-4fe9bfa8ea22ab856b50ffca42075599a83d7df1"
patches:
  - path: patch-deployment.yaml
  - path: patch-ingress.yaml

