apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../base
  - namespace.yaml

namespace: devops-lab-app-dev

images:
  - name: pipeops/devops-lab-app
    newName: docker.io/flaviopiccolo/devops-lab-app
    newTag: "sha-89abf43ea3b900dc933edbed380d8d41e559f48e"
patches:
  - path: patch-deployment.yaml
  - path: patch-ingress.yaml

