apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../base
  - namespace.yaml

namespace: devops-lab-app-dev

images:
  - name: pipeops/devops-lab-app
    newName: docker.io/flaviopiccolo/devops-lab-app
    newTag: "sha-b789483d76a1d94988aea79ec3aa5bc61d6ddb63"
patches:
  - path: patch-deployment.yaml
  - path: patch-ingress.yaml

