apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../base
  - namespace.yaml

namespace: devops-lab-app-dev

images:
  - name: pipeops/devops-lab-app
    newName: docker.io/flaviopiccolo/devops-lab-app
    newTag: "sha-5cc9771c92c9f2f8b5a106ebf306a9020389ee75"
patches:
  - path: patch-deployment.yaml
  - path: patch-ingress.yaml

