apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../base
  - namespace.yaml

namespace: devops-lab-app-dev

images:
  - name: pipeops/devops-lab-app
    newTag: "sha-bdfbce4846cf8bb923c7976f730d680352a176ce"
patches:
  - path: patch-deployment.yaml
  - path: patch-ingress.yaml

