apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../base
  - namespace.yaml

namespace: devops-lab-app-dev

images:
  - name: docker.io/flaviopiccolo/devops-lab-app
    newTag: "sha-f6387f3c751a6ebcf3081fc2030a51d472de341f"
patches:
  - path: patch-deployment.yaml
  - path: patch-ingress.yaml

