apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../base
  - namespace.yaml

namespace: devops-lab-app-dev

images:
  - name: pipeops/devops-lab-app
    newName: docker.io/flaviopiccolo/devops-lab-app
    newTag: "sha-131f1da4984d3e9f8315f384e7c3463aa93fb159"
patches:
  - path: patch-deployment.yaml
  - path: patch-ingress.yaml

