apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../base
  - namespace.yaml

namespace: devops-lab-app-dev

images:
  - name: pipeops/devops-lab-app
    newName: docker.io/flaviopiccolo/devops-lab-app
    newTag: "sha-6b619aa82916c865e73b03df3fecf6ab421bf35f"
patches:
  - path: patch-deployment.yaml
  - path: patch-ingress.yaml

