apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../base
  - namespace.yaml

namespace: devops-lab-app-dev

images:
  - name: pipeops/devops-lab-app
    newTag: "0.3.0"

patches:
  - path: patch-deployment.yaml
  - path: patch-ingress.yaml
