apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../base
  - namespace.yaml

namespace: devops-lab-app-dev

images:
  - name: pipeops/devops-lab-app
    newName: docker.io/flaviopiccolo/devops-lab-app
    newTag: "sha-19aecaa24020b414532d48161ff83a4133ea930c"
patches:
  - path: patch-deployment.yaml
  - path: patch-ingress.yaml

