apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../base
  - namespace.yaml

namespace: devops-lab-app-dev

images:
  - name: pipeops/devops-lab-app
    newTag: "sha-48a63ca3d494fb5eda9894599d57adb24f85bb34"
patches:
  - path: patch-deployment.yaml
  - path: patch-ingress.yaml
